name: kritastablediffusion
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy
  - pyinstaller=4.8
  - psutil=5.9.2
  - ncurses
  - pip:
      - tqdm==4.64.1
      - ftfy==6.1.1
      - pip-licenses==3.5.4
      - albumentations==0.4.3
      - diffusers
      - opencv-python==4.1.2.30
      - pudb==2019.2
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.2
      - pytorch-lightning==1.4.2
      - omegaconf==2.1.1
      - test-tube>=0.7.5
      - streamlit>=0.73.1
      - einops==0.3.0
      - torch-fidelity==0.3.0
      - transformers==4.19.2
      - torchmetrics==0.6.0
      - kornia==0.6
      - natsort==8.2.0
